### ISSUE TITLE
Source files 

### ISSUE THREAD

**Issue by krbrick** [Watts-College/cpp-528-spr-2022#16]
Hello - 
We are running into a problem with our source files. When we add our addition code to the source files, it messes with importing objects ('object not found' error). 
Is there a way to add less of the code to source files? Or to circumvent this problem? Are the source files required to include all the coding steps not required for knitting? 
Thanks a bunch,

**Comment by yukicruz** [comment]
The following would help more directly debug this issue:
 - A copy/paste of the error and the lines and/or chunks of the file(s) in which it occurs
 - A tree directory with your file names and directors
<br>  

Other thoughts and processes to help debug this issue and potentially others in the future:
 - Does the location that you've written in your file actually hold the files that you're trying to import? If your local directory looks even slightly different than your teammates' or the main repo then the file you're seeking might simply be in the wrong spot. Additionally, the file may be in a lab folder or child folder rather than a parent/sibling folder.
 - Are you copy/pasting code that is duplicatively calling sources? If so, some calls may be out of date or conflicting with other calls. Make sure the code you're adding does not conflict with existing code.
 - It is possible to put code in the .Rmd file rather than the .R file. However, I don't recommend that practice as it's not clean and prevents your files from being better organized--it is a workaround that doesn't fix the underlying issue and you will likely hit another similar snag as your code becomes longer or more complex. Still, if you need to do that to test code, you have the option of using <code>echo=FALSE</code> and <code>include=FALSE</code> in your .Rmd file's chunk headers to hide code and results, respectively, when you knit.
